github.com/shivankd814-debug/Satna-ea

shivankd814-debug / Satna-eat-

Code Issues

Pull requests

Agents

Actions

Projects Wiki

Security and qua

Get started with GitHub Actions

Build, test, and deploy your code. Make code reviews, branch management, and issue triaging wo started.

Skip this and set up a workflow yourself →

Q Search workflows

Suggested for this repository

Simple workflow

By GitHub

Start with a file with the minimum necessary structure.

Configure

Deployment

Deploy Node.js to Azure Web App

By Microsoft Azure

Build a Node.js project and deploy it to an Azure Web App.

Deploy to Amaz By Amazon Web S

Deploy a container Amazon EC2.

Configure

A

Deployment

Configure

Build and Deploy to GKE

By Google Cloud

Build a docker container, publish it to Google Container Registry, and deploy

to GKE.

Configure

Deployment

By HashiCorp

Terraform

Set up Terraform C

Configure

Deploy to Alibaba Cloud ACK

By Alibaba Cloud

Deploy a container to Alibaba Cloud Container Service for Kubernetes (ACK).

Deploy to IBM C By IBM

Build a docker com deploy to IBM Clou

Configure

Deployment

Configure

Tencent Kubernetes Engine

Ry Tencent Cloud

18

OpenShift
